### ISSUE TITLE
sdp_answer messages with no SSRC cause crashes in EndpointBin

### ISSUE THREAD

**Issue by sax** [membraneframework/membrane_webrtc_plugin#21]
I've been seeing occasional errors in our tests (using chromedriver), with the following stacktrace:

```
13:24:46.613 [error] GenServer #PID<0.1510.0> terminating
** (KeyError) key 2790623163 not found in: %{}
    :erlang.map_get(2790623163, %{})
    (membrane_webrtc_plugin 0.1.0) lib/membrane_webrtc_plugin/endpoint_bin.ex:236: Membrane.WebRTC.EndpointBin.handle_notification/4
    (membrane_core 0.6.1) lib/membrane/core/callback_handler.ex:129: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.6.1) lib/membrane/core/callback_handler.ex:70: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 0.6.1) lib/membrane/core/parent/message_dispatcher.ex:29: Membrane.Core.Parent.MessageDispatcher.handle_message/2
    (stdlib 3.15) gen_server.erl:699: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:775: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {Membrane.Core.Message, :notification, [:rtp, {:new_rtp_stream, 2790623163, 120}], []}
```

I've traced this to `sdp_answer` messages which do not include `ssrc` attributes. I've found that changing the `handle_other` callback for answers to check for this makes the crashes disappear, but am not sure if there are any unintended consequences:

```
    if ssrc_to_mid == %{} do
      {:ok, state}
    else
      {{:ok, forward: {:ice, {:set_remote_credentials, remote_credentials}}},
       Map.put(state, :ssrc_to_mid, ssrc_to_mid)}
    end
```

I'm happy to issue a pull request for this change, or to pull down changes if you want solve for this yourselves. Let me know if I can help!

**Comment by sax** [comment]
Maybe this is related to the issues?

https://bugs.chromium.org/p/webrtc/issues/detail?id=11983

**Comment by mickel8** [comment]
Hi @sax,
thanks for your investigation!

I am not sure if such SDP answers are incorrect. In fact `ssrc` attribute should be assigined by endpoint that sends data so maybe we should fix our parser. 

Is it possible to reproduce somehow this error?
Do you know when it happens?

**Comment by mickel8** [comment]
We also filter tracks to have only `:sendonly` ones https://github.com/membraneframework/membrane_webrtc_plugin/blob/master/lib/membrane_webrtc_plugin/endpoint_bin.ex#L298

so it's not exactly the case described on bugs.chromium.org

**Comment by sax** [comment]
One thing to note is that when the SDP messages came through with no ssrc, they were also missing `:sendonly`. `ssrc_to_mid` resolves to an empty map, causing a crash [here](https://github.com/membraneframework/membrane_webrtc_plugin/blob/master/lib/membrane_webrtc_plugin/endpoint_bin.ex#L236) when the notification bubbles up from the ice bin.

I think that I saw the error very occasionally when running the pipeline locally, connecting via a few Chrome windows. We've set up some feature tests using Wallaby with chromedriver, with the following configuration:

```elixir
config :wallaby,
  driver: Wallaby.Chrome,
  chromedriver: [
    capabilities: %{
      chromeOptions: %{
        args: [
          "--use-fake-ui-for-media-stream",
          "--use-fake-device-for-media-stream"
        ]
      }
    },
    headless: true
    # Uncomment below to run feature tests in-browser
    #    headless: false
  ],
  hackney_options: [hackney: [pool: false]],
  otp_app: :apex,
  screenshot_dir: "tmp/screenshots",
  screenshot_on_failure: true
```

With three browser sessions connecting to the video room, I could not get the tests to pass locally on Friday without some change. Our tests verify that candidates are received by each browser session, but not that inbound video tracks are successfully wired up.

**Comment by sax** [comment]
Also of note: I did not see these test failures prior to Friday, when I updated the following:

* ex_libnice: [`ec9cebbca102908e7f7bef069e0090fb041b077d` -> `97641db72e8eccb502c0929aa8d0da6fdff14ced`](https://github.com/membraneframework/ex_libnice/compare/ec9cebbca102908e7f7bef069e0090fb041b077d..97641db72e8eccb502c0929aa8d0da6fdff14ced)
* membrane_core: [`478fb7726ca85fe88d7bfb044cae290fa286c7d6` -> `153e86bade232c3095b032e405facf362acf2d2b`](https://github.com/membraneframework/membrane_core/compare/478fb7726ca85fe88d7bfb044cae290fa286c7d6..153e86bade232c3095b032e405facf362acf2d2b)
* membrane_rtp_plugin: [`37bd1f2d000444c35200d07363e85d53fb64eee4` -> `83981ab597c7101ec9c266f51b5bb65c5185ecc0`](https://github.com/membraneframework/membrane_rtp_plugin/compare/37bd1f2d000444c35200d07363e85d53fb64eee4..83981ab597c7101ec9c266f51b5bb65c5185ecc0)
* membrane_webrtc_plugin: [`54b2f2e33d924dfba3b9bff30ea74361855029b6` -> `2cd4a8395264894107b86043a5a996c4eca88e5c`](https://github.com/membraneframework/membrane_webrtc_plugin/compare/54b2f2e33d924dfba3b9bff30ea74361855029b6..2cd4a8395264894107b86043a5a996c4eca88e5c)

I'm poking around in these changesets to see if a change in the membrane plugins might have caused the problem, but I do not see an obvious culprit. Another possibility is that my version of Chrome upgraded. The timestamp on my Chrome executable is May 7, but I don't know if that's the install date, or the date it was compiled upstream.

**Comment by mickel8** [comment]
> One thing to note is that when the SDP messages came through with no ssrc, they were also missing :sendonly

I have to take a look at some RFCs to check it out but if I recall correctly lacking `direction` attribute (`sendrecv`, `sendonly`, `recvonly` or `inactive`) means we should assume `sendrecv` one but in such a case I would expect ssrc to be present.

We have also deployed videoroom and test it on different video calls but we didn't encounter similar problem.  

In your config there is a fake device for media stream but is it possible that no media were sent? I mean scenario with blocked microphone and camera. 

Also are you able to provide example SDP offer/answer from failing scenario?

I will dive more into RFCs describing SDP offer and answer formats but probably tomorrow.

**Comment by mickel8** [comment]
I haven't found anything about missing ssrc so far but I will take a look at  JSEP RFC tomorrow

**Comment by sax** [comment]
Here's an example of an answer with no SSRC:

```
v=0
o=- 329944319048971313 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 9FD4FB3AD296EE1D 91C8E2AFD848456C
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jYux
a=ice-pwd:avl7t/S9mUpAa8JPCrhu1R0j
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:9FD4FB3AD296EE1D
a=extmap:6 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=inactive
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jYux
a=ice-pwd:avl7t/S9mUpAa8JPCrhu1R0j
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:91C8E2AFD848456C
a=inactive
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 ccm fir
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
```

This was the offer generated by this process:

```
v=0
o=- 13757948492347214 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 9FD4FB3AD296EE1D 91C8E2AFD848456C
a=extmap:6 urn:ietf:params:rtp-hdrext:ssrc-audio-level vad=on
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=recvonly
a=ice-ufrag:FPdh
a=ice-pwd:1tujnqDBYWBGXvNQ2Tz5Xy
a=ice-options:trickle
a=fingerprint:sha-256 73:7B:02:0F:0B:B9:30:0D:BE:1A:E7:A6:C9:09:38:92:FE:EE:1E:5E:61:62:1D:36:19:F8:0A:0D:B9:F7:AB:FE
a=setup:actpass
a=mid:9FD4FB3AD296EE1D
a=msid:e5d02968-6f7a-42fe-9412-c52c4126e673 f034deb6-3e45-42dd-8ba2-5fb983e176b3
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=recvonly
a=ice-ufrag:FPdh
a=ice-pwd:1tujnqDBYWBGXvNQ2Tz5Xy
a=ice-options:trickle
a=fingerprint:sha-256 73:7B:02:0F:0B:B9:30:0D:BE:1A:E7:A6:C9:09:38:92:FE:EE:1E:5E:61:62:1D:36:19:F8:0A:0D:B9:F7:AB:FE
a=setup:actpass
a=mid:91C8E2AFD848456C
a=msid:e5d02968-6f7a-42fe-9412-c52c4126e673 8b389c2e-e081-45f3-bf51-5dae4f8c3682
a=rtcp-mux
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=rtcp-fb:96 ccm fir
a=rtcp-rsize
```

With the change in place to avoid crashes, the process then generates a new offer:

```
v=0
o=- 67208080129624285 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 9FD4FB3AD296EE1D 91C8E2AFD848456C C49A60E56DA2470F EEC6C5494B6784B5
a=extmap:6 urn:ietf:params:rtp-hdrext:ssrc-audio-level vad=on
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=recvonly
a=ice-ufrag:E9JQ
a=ice-pwd:D0flxfNzGFVr/PBdnApJdA
a=ice-options:trickle
a=fingerprint:sha-256 73:7B:02:0F:0B:B9:30:0D:BE:1A:E7:A6:C9:09:38:92:FE:EE:1E:5E:61:62:1D:36:19:F8:0A:0D:B9:F7:AB:FE
a=setup:actpass
a=mid:9FD4FB3AD296EE1D
a=msid:e5d02968-6f7a-42fe-9412-c52c4126e673 07e3fc0d-a914-4b4b-ab87-53a32bcfe340
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=recvonly
a=ice-ufrag:E9JQ
a=ice-pwd:D0flxfNzGFVr/PBdnApJdA
a=ice-options:trickle
a=fingerprint:sha-256 73:7B:02:0F:0B:B9:30:0D:BE:1A:E7:A6:C9:09:38:92:FE:EE:1E:5E:61:62:1D:36:19:F8:0A:0D:B9:F7:AB:FE
a=setup:actpass
a=mid:91C8E2AFD848456C
a=msid:e5d02968-6f7a-42fe-9412-c52c4126e673 d79fe39d-1788-4038-855e-0719d0804bfd
a=rtcp-mux
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=rtcp-fb:96 ccm fir
a=rtcp-rsize
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=sendonly
a=ice-ufrag:E9JQ
a=ice-pwd:D0flxfNzGFVr/PBdnApJdA
a=ice-options:trickle
a=fingerprint:sha-256 73:7B:02:0F:0B:B9:30:0D:BE:1A:E7:A6:C9:09:38:92:FE:EE:1E:5E:61:62:1D:36:19:F8:0A:0D:B9:F7:AB:FE
a=setup:actpass
a=mid:C49A60E56DA2470F
a=msid:2b7ee2e2-2d5f-4204-b7d6-10ce3b1ac940 8d009b36-99a0-4e81-bcda-41cf3f18ad0e
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 useinbandfec=1
a=ssrc:3499189166 cname:C49A60E56DA2470F-audio-2b7ee2e2-2d5f-4204-b7d6-10ce3b1ac940
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=sendonly
a=ice-ufrag:E9JQ
a=ice-pwd:D0flxfNzGFVr/PBdnApJdA
a=ice-options:trickle
a=fingerprint:sha-256 73:7B:02:0F:0B:B9:30:0D:BE:1A:E7:A6:C9:09:38:92:FE:EE:1E:5E:61:62:1D:36:19:F8:0A:0D:B9:F7:AB:FE
a=setup:actpass
a=mid:EEC6C5494B6784B5
a=msid:2b7ee2e2-2d5f-4204-b7d6-10ce3b1ac940 17b3332a-950a-4363-9f46-b0ce411bbaf7
a=rtcp-mux
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=rtcp-fb:96 ccm fir
a=rtcp-rsize
a=ssrc:3576231999 cname:EEC6C5494B6784B5-video-2b7ee2e2-2d5f-4204-b7d6-10ce3b1ac940
```

Which elicits this answer:

```
v=0
o=- 329944319048971313 5 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 9FD4FB3AD296EE1D 91C8E2AFD848456C C49A60E56DA2470F EEC6C5494B6784B5
a=msid-semantic: WMS lTpP8mY32BbIVsOByUrC7YyofuwubM5B536C
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:nvCE
a=ice-pwd:+iYZLQTbgBnLNfGwxWemWgTZ
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:9FD4FB3AD296EE1D
a=extmap:6 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendonly
a=msid:lTpP8mY32BbIVsOByUrC7YyofuwubM5B536C 792f7021-9f95-4ab4-a7f1-68ba0989a32d
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 minptime=10;useinbandfec=1
a=ssrc:435896142 cname:gWdd6i1/HATyVFuM
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:nvCE
a=ice-pwd:+iYZLQTbgBnLNfGwxWemWgTZ
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:91C8E2AFD848456C
a=sendonly
a=msid:lTpP8mY32BbIVsOByUrC7YyofuwubM5B536C 2e7acf50-5961-44c3-bbdf-1f8a1c99bf79
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 ccm fir
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=ssrc:2414121414 cname:gWdd6i1/HATyVFuM
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:nvCE
a=ice-pwd:+iYZLQTbgBnLNfGwxWemWgTZ
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:C49A60E56DA2470F
a=extmap:6 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:nvCE
a=ice-pwd:+iYZLQTbgBnLNfGwxWemWgTZ
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:EEC6C5494B6784B5
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 ccm fir
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
```

**Comment by mickel8** [comment]
> Here's an example of an answer with no SSRC:
> v=0
o=- 329944319048971313 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 9FD4FB3AD296EE1D 91C8E2AFD848456C
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jYux
a=ice-pwd:avl7t/S9mUpAa8JPCrhu1R0j
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:9FD4FB3AD296EE1D
a=extmap:6 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=inactive
a=rtcp-mux
a=rtpmap:120 OPUS/48000/2
a=fmtp:120 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jYux
a=ice-pwd:avl7t/S9mUpAa8JPCrhu1R0j
a=ice-options:trickle
a=fingerprint:sha-256 5C:80:6D:DC:DB:F2:03:BA:E7:33:64:E3:26:38:E3:FE:D0:4A:20:79:19:BB:87:60:38:C9:10:15:2E:6F:7C:AD
a=setup:active
a=mid:91C8E2AFD848456C
a=inactive
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 ccm fir
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

The answer marks both tracks as `inactive` which means no media will be sent on any of them. I think that this might be a reason of missing ssrc :thinking:

**Comment by mickel8** [comment]
> With the change in place to avoid crashes, the process then generates a new offer:

Could you elaborate? Is it your change in source code that generates a new SDP offer?

**Comment by sax** [comment]
> Could you elaborate? Is it your change in source code that generates a new SDP offer?

This is with #22 applied. Our pipeline does not have any special code, but if we ignore the answer in the `EndpointBin`, I see a second offer generated by the same process, and an answer to that with ssrc included.
