### ISSUE TITLE
Unsupported parameter with Chrome Version 107

### ISSUE THREAD

**Issue by philipgiuliani** [membraneframework/membrane_webrtc_plugin#97]
With the Google Chrome Update 107 users cannot join our WebRTC room. It crashes with the following error:

```
2022-10-26T06:07:04 06:07:04.771 [info] New peer: %Membrane.RTC.Engine.Peer{id: "51a18c65-7d20-4453-aa61-ba7df19d2ae1", metadata: %{"displayName" => "..."}}. Accepting.
2022-10-26T06:07:04 06:07:04.894 [error] GenServer #PID<0.3538.0> terminating
2022-10-26T06:07:04 ** (MatchError) no match of right hand side value: {:error, {:unsupported_parameter, "m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 122 127 121 125 107 108 109 124 120 39 40 41 42 43 44 45 46 47 48 123 119 114 115 116 49"}}
2022-10-26T06:07:04     (membrane_webrtc_plugin 0.8.0-rc.1) lib/membrane_webrtc_plugin/endpoint_bin.ex:619: Membrane.WebRTC.EndpointBin.handle_other/3
2022-10-26T06:07:04     (membrane_core 0.10.2) lib/membrane/core/callback_handler.ex:140: Membrane.Core.CallbackHandler.exec_callback/4
2022-10-26T06:07:04     (membrane_core 0.10.2) lib/membrane/core/callback_handler.ex:65: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
2022-10-26T06:07:04     (membrane_core 0.10.2) lib/membrane/core/bin.ex:217: Membrane.Core.Bin.handle_info/2
2022-10-26T06:07:04     (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
2022-10-26T06:07:04     (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
2022-10-26T06:07:04     (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2022-10-26T06:07:04 Last message: {:signal, {:sdp_offer, "v=0\r\no=- 258784669936673572 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:15IR\r\na=ice-pwd:Km/Q54k5JO4SAseNgKRK3gWk\r\na=ice-options:trickle\r\na=fingerprint:sha-256 FF:0C:0B:24:4C:4B:DC:B5:2A:6A:8C:D5:8F:34:E1:29:8F:D2:68:89:5D:02:E8:E1:D9:96:D4:B0:E5:19:56:04\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:63 red/48000/2\r\na=fmtp:63 111/111\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 122 127 121 125 107 108 109 124 120 39 40 41 42 43 44 45 46 47 48 123 119 114 115 116 49\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:15IR\r\na=ice-pwd:Km/Q54k5JO4SAseNgKRK3gWk\r\na=ice-options:trickle\r\na=fingerprint:sha-256 FF:0C:0B:24:4C:4B:DC:B5:2A:6A:8C:D5:8F:34:E1:29:8F:D2:68:89:5D:02:E8:E1:D9:96:D4:B0:E5:19:56:04\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:35 VP9/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=fmtp:35 profile-id=1\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:37 VP9/90000\r\na=rtcp-fb:37 goog-remb\r\na=rtcp-fb:37 transport-cc\r\na=rtcp-fb:37 ccm fir\r\na=rtcp-fb:37 nack\r\na=rtcp-fb:37 nack pli\r\na=fmtp:37 profile-id=3\r\na=rtpmap:38 rtx/90000\r\na=fmtp:38 apt=37\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-a" <> ..., %{}}}
2022-10-26T06:07:04 06:07:04.895 [error] Endpoint "51a18c65-7d20-4453-aa61-ba7df19d2ae1" has crashed!
2022-10-26T06:07:04 06:07:04.896 [warning] [:ice_funnel] Terminating element possibly not prepared for termination as it was in state :playing.
2022-10-26T06:07:04 Reason: {{:badmatch, {:error, {:unsupported_parameter, "m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 122 127 121 125 107 108 109 124 120 39 40 41 42 43 44 45 46 47 48 123 119 114 115 116 49"}}}, [{Membrane.WebRTC.EndpointBin, :handle_other, 3, [file: 'lib/membrane_webrtc_plugin/endpoint_bin.ex', line: 619]}, {Membrane.Core.CallbackHandler, :exec_callback, 4, [file: 'lib/membrane/core/callback_handler.ex', line: 140]}, {Membrane.Core.CallbackHandler, :exec_and_handle_callback, 5, [file: 'lib/membrane/core/callback_handler.ex', line: 65]}, {Membrane.Core.Bin, :handle_info, 2, [file: 'lib/membrane/core/bin.ex', line: 217]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]},
2022-10-26T06:07:04 State: %Membrane.Core.Element.State{
2022-10-26T06:07:04   module: Membrane.Funnel,
...
```

**Comment by philipgiuliani** [comment]
Moved to https://github.com/membraneframework/ex_sdp/issues/24
